settings:
  replace-bucket: false
  click-menu: true
  default-faction-name: 'wilderness'

  #No Gen in wilderness
  allow-wilderness-gen: false

  # The max amount of GenBucket iterations allowed at once
  # This will only pause the generation process and not cancel placement.
  max-buckets: 25000

  # If someone drops a GenBucket item we remove it
  clear-drops: true

  # Speed of the GenBucket, 5 = 5 ticks = 0.25 seconds
  tick-speed: 5

  # If a GenBucket is placed at Y:60 or above, the vertical GenBucket will gen downward. If below Y:60 It will gen upwards.
  vertical-switch: 60

  # Allow use of /gb to open the main menu for non-op'd players
  use-replace-command: true

  test-command:
    # Only these worlds can run the /gen test Command
    whitelisted-worlds:
      - 'someworldnamehere'

menu-design:
  title: "&a&lGENBUCKET MENU"
  rows: 4
  background: BLACK_STAINED_GLASS_PANE

messages:
  error-permission: "&cNot enough permissions."
  error-no-money: "&cYou do not have enough money to place a GenBucket!"
  error-whitelist: "&cThis world is currently not whitelisted for the /gen test command!"
  error-not-player: "&cOnly players may execute this command"
  gen-wilderness: "&c You cannot use a GenBucket in Wilderness!"
  player-cant-gen-here: "&c You cannot use a GenBucket here!"

genbuckets:
  CobbleVertical:
    #Will this be able to continue through water and lava?
    bypass-lava-water: true

    # Will this material be pseudo? Will it go through it's own material?
    patch: false

    # The type of material generated by the GenBucket when placed
    material: COBBLESTONE

    # What slot in the GUI do we want the bucket to be in ?
    menu-slot: 12

    # How much per placement do we want the GenBucket to be?
    bucket-cost: 200

    # What kind of item to we want to start the GenBucket? HINT: This can be blocks
    bucket-item: LAVA_BUCKET

    # The display name of the generator item
    bucket-name: "&7&lCobblestone Vertical"

    # Verical or Horizontal
    bucket-type: Vertical

    # The description of the GenBucket
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"

  ObsidianPatch:
    bypass-lava-water: true
    patch: true
    material: OBSIDIAN
    menu-slot: 13
    bucket-cost: 250
    bucket-item: LAVA_BUCKET
    bucket-name: "&7&lObsidian Patch"
    bucket-type: Vertical
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"
  CobbleHorizontal:
    bypass-lava-water: false
    material: COBBLESTONE
    menu-slot: 14
    bucket-cost: 250
    bucket-item: LAVA_BUCKET
    bucket-name: "&7&lCobblestone Horizontal"
    bucket-type: Horizontal
    bucket-size: 16
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"
  ObsidianPrintable:
    patch: false
    material: OBSIDIAN
    menu-slot: 22
    bucket-cost: 250
    bucket-item: OBSIDIAN
    bucket-name: "&7&lObsidian Printable"
    bucket-type: Vertical
    bucket-lore:
      - "&7&o(Placing this bucket will generate a wall)"
      - ""
      - "&2&l\u27A5 &a&lBUCKET TYPE: &7[TYPE]"
      - "&2&l\u27A5 &a&lBUCKET COST: &7$[COST]"